admin_password = "depanalise"

[gcp_service_account]
type = "service_account"
project_id = "interfacevasco"
private_key_id = "b93693f95bb3ba1f3988ed2706ae3b7b4a181dc4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCrx/FFLgeiy38g
XkVY1NGCYt/LmT7yKpW8eaVNNadflF4kJjTL/VEHKgkupKyct70YersXst60ldjJ
QXqpLrT5kj7eoOKhwA4tLjW127VqgMv7XduyYM90VAT3o1NgqCQxBmxlnBzZHaHJ
Ynkvt01N29eKL/RJtHC1+wXtcvmqWeQiKZR/ny0AWRvTBfjfr1DdooPTAWdDQCqo
EXtosSRYjT/hlOrlS8grsqXFZHarmuAiyg6SRC9+6hJjckeIcjPr+vRbQmsagBW4
xk7V/O18PndvzbOowue/nKq2/29Et7jx/oXVMFYJjbA0lZhOGZwZ1WEFc9u7oEa6
tPKaIh7DAgMBAAECggEABnBVplKt3ZfEGZn+/m/ntHvxSIfjeJ9JAooKvKSks+vz
RWabNwQ1O9ADDRkGEU+/ykGbbq15NIqjWBPYvauvA+XL7ntYU1jID0B6qejk2Wuf
eboQaJTBYepeT0vzbZ2P0bicaoiZ+jdmn45N3ZCA2MjDQP5AKV0WlnOkyrwzCIQL
Sh+1rwn0hLiPxrd8m3zRx6piquSK7Y3FPfNtS4MUgUeS9en7T1MzM22CATn2AZmf
++FFFGQrJvoom4lHoHkRV3qixYEuqEqIVNubVdpk5JqHpDt8spg7tIIW1zIpoWsh
0XuP/Zw8Vq3aSX4Dn5NDkefC2dumq27EoeRfzoLsNQKBgQDhuX+Ofzf7s2qJuN4I
Ub/s1Mjvc+1YCNMiZSMWIfYwSOO39qFQsMq0w7HNyzv57SdMw8S/2zd69rB2Wmaa
HNMbMNbgE22XgxEZmHg9c1rwrbPzdJxXOpwJRG0P63EZHTdutM3sp01Nsxm9Va+g
8ewkr/pRrPphxwD62N/+dC5FrQKBgQDC0jt5IaH2gX/K0Ts8ygWPcOPB/OMzvrQ7
Mt1iGqk8PldwGzVWbzo1QyRjLodmv6LhN89hnOsXhQOeQW/PNhZwrqM+1ku3j5kF
rFJsu4C3xAYI7hnDl8rRReb71xI8j7066F9kleuVWOHLBnfM/PA5259EU14rbA6k
PQSO+BMkLwKBgDBP7rBGJGpYBWaCzesD7Es5Y+R0cIlWIjKLaQ4UqMe+4hZ+0Bog
LNKxy/2bETQ2ASJaCGNz/RTxdeVvBeTYZIq+Uk9VeTBjmiZbTukAJqe61fg2rjux
TLJjFeDBaMySR0oHoseTK2WE/u5aR6PwA7X6gF444sJIwLnv70lb/odlAoGBAISM
ntQqUtSxhO3L7z7LwH64cu1wDnENRfilAcSWmSAY1kq66E43fOXyGZa1eIAq0Dnl
S96A8d5drHmG0fisNxZRa1X8XSW1uIoIlUfPRqNA5k47GSJfayl5Is+jo4+6yCeF
JCn+anuBLpaAfw/j49mpmDHXetGWQlvx++D93aAXAoGBAL1l5q98DimZ/TqiJDry
Vt1GsuX4s35cYGvigoeRlQq3aceWgVj8TFkVueXyh6fXjYs4R3VYh5uvLSwaQ0eC
wHfVxwfDDLeITHCxHTXuB8tHiVsYR4OoK4oW4spAKHiFyq2lL39CQNdxQ3f2RzrW
DPWhRDIGhjYB94F+lT87leYF
-----END PRIVATE KEY-----"""
client_email = "acesso-planilha-vasco@interfacevasco.iam.gserviceaccount.com"
client_id = "103690769733973467675"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/acesso-planilha-vasco%40interfacevasco.iam.gserviceaccount.com"
universe_domain = "googleapis.com"